### ISSUE TITLE
Custom legend is not visible - FIXED

### ISSUE THREAD

**Issue by SylvainBertrand** [GSI-CS-CO/chart-fx#104]
Hi!
Thanks for providing this great alternative for charts with JavaFX, the struggle has been real!

Ok so the issue is rather simple: when setting the legend of a `XYChart`, this legend is not visible unless you cycle the `Chart.legendVisible` property. The issue shows up for any legend implementation, even `DefaultLegend`.

I'm depending on the version 8.1.1.

I used `SimpleChartSample` to highlight the issue, here is the code:
```
package com.example.chartfx;

import de.gsi.chart.XYChart;
import de.gsi.chart.axes.spi.DefaultNumericAxis;
import de.gsi.chart.legend.spi.DefaultLegend;
import de.gsi.dataset.spi.DoubleDataSet;
import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.layout.StackPane;
import javafx.stage.Stage;

public class SimpleChartSample extends Application {
    private static final int N_SAMPLES = 100;

    @Override
    public void start(final Stage primaryStage) {
        final StackPane root = new StackPane();

        final XYChart chart = new XYChart(new DefaultNumericAxis(), new DefaultNumericAxis());
        root.getChildren().add(chart);

        // The new legend is not visible
        chart.setLegend(new DefaultLegend());
        // Uncomment the following 2 lines to enable current workaround:
//        chart.setLegendVisible(false);
//        chart.setLegendVisible(true);


        final DoubleDataSet dataSet1 = new DoubleDataSet("data set #1");
        final DoubleDataSet dataSet2 = new DoubleDataSet("data set #2");
        // lineChartPlot.getDatasets().add(dataSet1); // for single data set
        chart.getDatasets().addAll(dataSet1, dataSet2); // two data sets

        final double[] xValues = new double[N_SAMPLES];
        final double[] yValues1 = new double[N_SAMPLES];
        final double[] yValues2 = new double[N_SAMPLES];
        for (int n = 0; n < N_SAMPLES; n++) {
            xValues[n] = n;
            yValues1[n] = Math.cos(Math.toRadians(10.0 * n));
            yValues2[n] = Math.sin(Math.toRadians(10.0 * n));
        }
        dataSet1.set(xValues, yValues1);
        dataSet2.set(xValues, yValues2);

        final Scene scene = new Scene(root, 800, 600);
        primaryStage.setTitle(this.getClass().getSimpleName());
        primaryStage.setScene(scene);
        primaryStage.setOnCloseRequest(evt -> System.exit(0));
        primaryStage.show();
    }
    public static void main(final String[] args) {
        Application.launch(args);
    }
}
```

**Comment by RalphSteinhagen** [comment]
Hi!

Thanks for reporting and providing a short example. This helped and sped up fixing this a lot. 

The new custom `Legend` was added to the wrong (super) pane (error in the corresponding ObjectProperty implementation) and subsequent cycling through the `Chart.legendVisible` property triggered the correct code. Should be fixed now in the rstein-feature branch and merged into master soon (< a week). Let us know if this fixes your problem. Thanks in advance.

May I ask what type of custom Legend you have? We are aware that the present DefaultLegend implementation isn't ideal and would appreciate some "love". Maybe your version is worthwhile to be added/merged? Let us know.

Thanks again!

**Comment by SylvainBertrand** [comment]
Awesome!
Thanks for the quick response!

The legend I implemented is quite specific to the application, not sure if that'd be desired for other applications:
![B3E15xv3lG](https://user-images.githubusercontent.com/15932806/75167782-85c7f980-56eb-11ea-9136-421159c4ae4b.gif)

As you can see, the charts are being stripped to the bare minimum, the goal is to be able to plot up to 24 charts per window, so space has to be optimized. The legend includes the display of variable's current value.

**Comment by RalphSteinhagen** [comment]
I see. You seem to follow a minimalist approach and need plotting performance.

**Comment by SylvainBertrand** [comment]
Exactly and JavaFX's been beating me down with the performance issue.
I got an interest about your (possibly long term) objective of tackling down the performance issue of JavaFX and would like to talk about it. Not sure what's the right place and person to do discuss that, could you direct me please?

**Comment by RalphSteinhagen** [comment]
@SylvainBertrand, certainly. Am curious about your use-case. You may contact me at my @GSI address. We are also dealing with real-time signal processing and feedback and using Java/JavaFX (on the desktop) as an unusual use-case as well.

**Comment by RalphSteinhagen** [comment]
fixed and merged to master
