### ISSUE TITLE
Specified TickUnit has no effect on time axis (DefaultNumericAxis)

### ISSUE THREAD

**Issue by zanzica** [GSI-CS-CO/chart-fx#129]
Hi,

I noticed that the TickUnit does not seem to have any effect on a time x axis (DefaultNumericAxis). I attached an example.

When setting tick unit to 30 (seconds), I would expect to see tick marks every 30 seconds, however I see tick marks every minute. 

I traced the problem to AbstractAxis#layoutChildren, line 1255:
`setTickUnit(computePreferredTickUnit(axisLength));`
As far as I can see, this always recomputed the tick unit - even when a tick unit has been specifically set by the user.

If I change this line to
`setTickUnit(getTickUnit());`
I get the expected behaviour.

Example:
[DEMO_TickUnit.txt](https://github.com/GSI-CS-CO/chart-fx/files/4356288/DEMO_TickUnit.txt)

Actual:
![2020-03-19_DemoTickUnit_30_withoutChange](https://user-images.githubusercontent.com/14939118/77100609-389f2500-6a16-11ea-9eca-d03e88b8f2fc.png)

Expected/after adapting AbstractAxis:
![2020-03-19_DemoTickUnit_30_withChange](https://user-images.githubusercontent.com/14939118/77100619-3dfc6f80-6a16-11ea-9bff-53832b84f4e7.png)

**Comment by RalphSteinhagen** [comment]
@zanzica thanks for reporting. The fix is not quite as trivial without breaking the other use-cases. Hope that I found a good compromise. See also PR #131

**Comment by zanzica** [comment]
I just noticed that the Javadoc for DefaultNumericAxis states:

```
Compared to the {@link NumberAxis}, this one has a few additional features:
* Re-calculates tick unit also when the {@link #autoRangingProperty() auto-ranging} is off</li>
```

Is/was this supposed to be the correct behaviour?

**Comment by RalphSteinhagen** [comment]
yes, until you opened this issue. ;-)

The main original rationale was that one needs to (must) recompute the tick-unit if one zooms, drags or changes the axis range (e.g. sliding/increasing time-axis).

**Comment by zanzica** [comment]
I can confirm that the changes fixed this issue, thanks! Closing this issue as discussed with @wirew0rm .

**Comment by zanzica** [comment]
Unfortunately I realized that the implemented fix breaks working with custom TickUnitSuppliers. :-( 
I'm reopening this issue (because this is related to its fix), but feel free to move this into a separate issue if it suits you better.

The use case for which I created a custom TickUnitSupplier is that I am working with timestamps in nanoseconds, and wanted to define custom tick units based on the range (instead of defining a static TickUnit).

In the attached example, the x axis unit (seconds -> millis -> micros -> nanos) can be configured with the "multiplier" variable.
[DEMO_TickUnitSupplier.txt](https://github.com/GSI-CS-CO/chart-fx/files/4376695/DEMO_TickUnitSupplier.txt)

The example works fine with revision 5385755 (before the fix was merged): For all x axis units, there are three tick marks visible, showing the correct time. (Screenshot is for nanoseconds, the others look the same.)
![2020-03-24_DemoTickUnitSupplier_correct_nanos](https://user-images.githubusercontent.com/14939118/77455955-d7eb6000-6dfa-11ea-90ad-59eeae354dac.png)

The example is broken in revision d73b66c (when the fix was merged): It works correctly for seconds (but shows "stripes"? -> screenshot, hangs for millis and micros, then eventually shows chart (but does not show x tick labels), and show up quickly but does not display x tick labels for nanos (-> screenshot).
![2020-03-24_DemoTickUnitSupplier_broken_seconds](https://user-images.githubusercontent.com/14939118/77455961-dae65080-6dfa-11ea-9a61-a266916afd69.png)
![2020-03-24_DemoTickUnitSupplier_broken_nanos](https://user-images.githubusercontent.com/14939118/77455964-dd48aa80-6dfa-11ea-99fa-ae0688165b0b.png)

When x tick labels are not displayed, I see the following log message:
`DEBUG [24 Mar 2020 18:01:55,831] (DefaultLoggingEventBuilder.java) - major ticks numerically not resolvable`
This leads back to DefaultNumericAxis#calculateMajorTickValues:
`if (firstTick + axisRange.getTickUnit() == firstTick) {
            if (LOGGER.isDebugEnabled()) {
                LOGGER.atDebug().log("major ticks numerically not resolvable");
            }
            return tickValues;
}`
As no tick unit was explicitly specified (since it was now expected to be handle by the TickUnitSupplier, `axisRange.getTickUnit()` defaults to 5. This offset is lost due to double precision when we compare `firstTick + axisRange.getTickUnit() == firstTick` when the double value for firstTick is sufficiently large (for x unit >= millis).

I am not sure how to fix this properly to make both static tick units and TickUnitSuppliers work correctly. 
Personally, I would suggest reverting the current "fix" for the original issue for now - always recalculating the tick unit was, apparently, the intended behaviour and even documented in the Javadoc (even though it confused me when I tried to set the tick unit explicitly - maybe the Javadoc for #setTickUnit should give users a heads-up?). I think the TickUnitSupplier functionality is quite elegant and flexible, and I would currently prefer having TickUnitSuppliers work correctly over having static TickUnits work correctly ...

**Comment by wirew0rm** [comment]
Reverted back to the original behaviour, thanks for the detailed error description.

Regarding documentation, it is unfortunately not as simple as updating the Javadoc, since this the documented behaviour is correct for the other axis implementations. We will have to think about this some more.
