### ISSUE TITLE
Is it possible to change the marker size based on data?

### ISSUE THREAD

**Issue by soloman817** [GSI-CS-CO/chart-fx#15]
So, it is more like a 3d dataset, x is time, y is the location, and z is the value. I would like to plot it at a 2D chart, with x and y the location is decided, and z value controls the marker size.

Any idea?

**Comment by RalphSteinhagen** [comment]
The marker shape/size handling is still very basic but useful for 'bubble chart'-type renderer. 

We have a similar use-case at GSI/FAIR in the intermediate pipe-line*.

There are two aspects to it:
1. data-storage: 
    * one option is to store the '(x, y, z resp. marker size)' tuples using the DataSet3D interface. N.B. Alexander is already reworking a similar related feature (renaming of 'DataSet3D -> GridDataSet', and ContourRenderer/MountainRangeRenderer adaptations).
    * alternatively, the size information could be stored in the point-specific data style fields (e.g. "markerSize=10; markerStyle=box") and the (new) renderer reading these properties
2. rendering: writing the renderer should be relatively easy and could be based on an existing renderer. I would propose to name it 'BubbleDataSetRenderer'.

Some open questions are:
* usage of 'grid-based 3D' vs. 'labels/styles-based 2D' data sets
* is point-reduction/regrouping required (e.g. via deriving from ErrorDataSetRenderer)
* optimisation goal in terms of number of points/bubbles/marker to be drawn.

How many points do you expect for your use-case?


*P.S. GSI-intern use-case: BTM display -- plotting 'transmission-efficiency vs. intensity' and bubble-size being related to the relative frequency in time the accelerator operated at the given (transmission, intensity) pair.

**Comment by RalphSteinhagen** [comment]
New functionality is in the master and JDK8 branch. Please note that for the time being the datasets need to be sorted by their x coordinates. Enjoy!
