### ISSUE TITLE
The second y axis cannot zoom in/out

### ISSUE THREAD

**Issue by soloman817** [GSI-CS-CO/chart-fx#16]
so in example: https://github.com/GSI-CS-CO/chart-fx/blob/master/chartfx-samples/src/main/java/de/gsi/chart/samples/MultipleAxesSample.java

If I lock the zoomed to only zoom Y axis, and then scroll the mouse, only the left y-axis (the first y axis) zooms, the 2 other y axis doesn't change. 

Is there way to select which y-axis to zoom?

**Comment by RalphSteinhagen** [comment]
Not yet. This is a missing functionality in the Zoomer plugin that for the time being tracks only changes of the first primary axes for X and Y.

https://github.com/GSI-CS-CO/chart-fx/blob/a67b98c8224bdaccb627b60c123e4570cff1b17b/chartfx-chart/src/main/java/de/gsi/chart/plugins/Zoomer.java#L821-L832

The functionality seems to be limited to above function (+ ZoomState tracking) and would need to be extended to 
   * loop through all axes, 
   * track changes and performs the zoom for each one, and
  * ideally with a boolean flag that controls whether the axis is taken into account.

The first two items should be easy to do and do not require API changes (ie. zooming always for all axes). The boolean flag for specific axes may need a Zoomer plugin API extension. Should be robust enough to handle axes being added/removed during intermediate zoom states.

The MutipleAxesSample is sufficient for testing/documenting the new functionality.

**Comment by RalphSteinhagen** [comment]
some addition: whether a axis should be taken into account for zooming or not could be controlled with the following marks:

https://github.com/GSI-CS-CO/chart-fx/blob/a67b98c8224bdaccb627b60c123e4570cff1b17b/chartfx-chart/src/main/java/de/gsi/chart/plugins/Zoomer.java#L971-L975

I presume that one would need one ZoomState object per Axis, ie.

https://github.com/GSI-CS-CO/chart-fx/blob/a67b98c8224bdaccb627b60c123e4570cff1b17b/chartfx-chart/src/main/java/de/gsi/chart/plugins/Zoomer.java#L123

being a ArrayDeque of a List of ZoomState (one per y-axis).

**Comment by RalphSteinhagen** [comment]
@soloman817 if you like to check the prototype implementation. We may merge this with the master/JDK production branch by next week.
https://github.com/GSI-CS-CO/chart-fx/tree/feature-zoomer-extension

**Comment by soloman817** [comment]
@RalphSteinhagen Thanks, and I compiled the multi axes sample and ran it. Looks good, but one issue, if I check 'include the 3rd axis', and select the 4th button (to only zoom y-axis) then if I scroll mouse, the 3rd axis value looks strange, they are not centered in the middle.

**Comment by soloman817** [comment]
BTW, if it is merged, can it support Java8?

**Comment by RalphSteinhagen** [comment]
> BTW, if it is merged, can it support Java8?

Yes, just cherry-picked the feature to the JDK branch... Maven Central release will come later (maybe next week). Enjoy!
