### ISSUE TITLE
setLegendVisible(false) does not hide legend

### ISSUE THREAD

**Issue by karlduderstadt** [GSI-CS-CO/chart-fx#182]
After updating to version 8.1.4 the setLegendVisible(false) function of Chart no longer completely hides the legend. You can see from the clipping at the bottom, a white box remains:

![Screenshot 2020-05-09 at 09 51 50](https://user-images.githubusercontent.com/17951396/81467692-b8f23300-91da-11ea-95be-c8b74e95e579.png)

Using setLegend(null) does hide the legend. But then a warning message appear every time a chart is created:

![Screenshot 2020-05-09 at 09 53 46](https://user-images.githubusercontent.com/17951396/81467738-01a9ec00-91db-11ea-8698-ec225666c2b4.png)

Is there a way to prevent this message from showing up?

Once again, thanks very much for this wonderful charting library!

**Comment by RalphSteinhagen** [comment]
@karlduderstadt, sorry for getting back late. It should be fixed now.

There was a spurious `System.err.println(..)` left in the code and the Legend added/removed from the wrong sub-pane in case of setting the Legend (in-)visible.

**Comment by karlduderstadt** [comment]
Hi @RalphSteinhagen,
Great! Thanks! I will give the snapshot build a shot and then close the issue if everything is resolved.

**Comment by RalphSteinhagen** [comment]
@karlduderstadt we just released a new version of chart-fx with the above-mentioned fixes in place. I would thus close this issue.

Please feel free to reopen this issue if there are still problems.
