### ISSUE TITLE
What's the best way to change the tooltip label css style?

### ISSUE THREAD

**Issue by soloman817** [GSI-CS-CO/chart-fx#19]
Sorry that I'm also not familiar with JavaFX, now I am using the Tooltip plugin, and I found that the style control is in `de.gsi.chart.chart.css` resource, there is a `.chart-datapoint-tooltip-label`, I would like to change the alignment from `center` to `left`. What's the suggested way to override that from coding?

**Comment by RalphSteinhagen** [comment]
You may want to have a look at [JavaFX docs](https://docs.oracle.com/javafx/2/css_tutorial/jfxpub-css_tutorial.htm).

In your case, you need to write your own `.css` stylesheet and load it to the chart prior to adding  the 'DataPointTooltip' plugin. 
E.g. with a `CustomDataToolTip.css` CSS stylesheet containing only the following lines
```
.chart-datapoint-tooltip-label { 
    -fx-text-alignment: left;
}
```
and adding this via the `getStylesheets().add(...)` call prior to adding the plugin
```
private static final String CUSTOM_CSS = YourClass.class.getResource("CustomDataToolTip.css").toExternalForm();
// [..]
chart.getStylesheets().add(CUSTOM_CSS);
// [..]
```
should do the trick. Hope this helps and gets you going. 

N.B. [StackOverflow](https://stackoverflow.com/search?q=JavaFX+custom+stylesheet) is a good source for this type of question.

**Comment by soloman817** [comment]
Thanks a lot, it works, sure, next time I will check StackOverflow
