### ISSUE TITLE
CrosshairIndicator Label not updated on mouse-move using JMetro

### ISSUE THREAD

**Issue by deepthought-64** [GSI-CS-CO/chart-fx#231]
After some time i got back to working on my UI Project. :)

I added the `de.gsi.chart.plugins.CrosshairIndicator` plugin to a chart. The lines (`crosshairPath`) works as expected. 
But the label (`coordinatesLabel`) is not updated on mouse-move but only when i zoom in/out of the chart. 

Best see a short video as demonstration:
![chart-label-issue2](https://user-images.githubusercontent.com/5528887/90005540-a6830c00-dc97-11ea-9b2e-9564c06815a5.gif)
You see at the beginning it does not show the text at all, but only after i zoomed out, it rendered the label. But then it got stuck on one value until the next zoooming.

I checked to verify that the method `private void updateLabel(final MouseEvent event, final Bounds plotAreaBounds)` in`CrosshairIndicator` is actually invoked and also calls `coordinatesLabel.setText()` with the correct updated string. 
I have no clue why it is not rendered on the graph.

I tried removing the Zoomer-Plugin to see if that may block it, but it did not work.

I would appreciate if you could help me.

I am using 
- JDK: OpenJDK 14.0.1
- JavaFX 13.0.2
- chart-fx: 11.1.5
- OS: Linux 5.7.12-arch1-1

**Comment by RalphSteinhagen** [comment]
@deepthought-64 sorry for the delayed reply. Unfortunately, I seem to be unable to reproduce this. Do you see this in any of the sample applications?

Could you, for example, add the `CrosshairIndicator` plugin to the `SimpleChartSample` and retry with master? Did you modify the listener? Just in case, could you also check against 'master' and/or the 'dev-x.2.0' branch? The latter will be merged soon into 'master'.

**Comment by deepthought-64** [comment]
I havet to apologzie too for my late reply... Was on holidays and then had some hectic days. Will check your sugestions out today. Maybe it has something to do with the JRE version i am using or the fact that i am using Linux.

**Comment by RalphSteinhagen** [comment]
@deepthought-64 no worries... if it's a genuine bug it'll be fixed. Am using Linux also but simply couldn't reproduce it with the examples we had using this plugin. An MVP example would be appreciated. :+1:

**Comment by deepthought-64** [comment]
Okay, will try to put something together.
Btw, just found something else (#238) but I don't think that is related

**Comment by deepthought-64** [comment]
I have added a MVP to https://bitbucket.org/fabian_kasper/gsi-cs-co-chart-fx-231-mvp/src/master/
I could isolate the problem. It looks like as soon as i enable [JMetro](https://www.pixelduke.com/java-javafx-theme-jmetro/) the bug appears... But i don't really know why that is happening

by the way, i hope that it is not too much of an inconveniance that the project is koltin. I use tornadofx (kotlin javafx framework) and therefore i thought the MVP should be kotlin too.

**Comment by RalphSteinhagen** [comment]
@deepthought-64 thanks a lot for the MVP which helped a lot! :+1:

Will need to look into a bit more detail about why JMetro suppresses the event listener.

We seem to have identified the source for issue #238.

**Comment by deepthought-64** [comment]
The way I see it, is not that the event listener is surpressed (because then the crosshair would also not move) but the label is not rendered anymore. I see that it has it's managed property set to false, so maybe that has something to do with it?

**Comment by RalphSteinhagen** [comment]
@deepthought-64 thanks again for reporting, should be fixed now through a workaround replacing `Label` (which is derived from `Control` with `Text`(deriving more directly from `Node`, see PR for details). It seems that the label text content wasn't updated part of the scene graph once the JMetro is enabled. The root cause seems to be rather in the JavaFX framework and/or JMetro. In any case, the workaround should mitigate this.

Let us know if you can confirm the fix, we'll merge this to master and release this during the next opportunity.

**Comment by deepthought-64** [comment]
Hi @RalphSteinhagen 

thank you very much for taking the time to fix that. I have tested it against `fix-issues-231-238-SNAPSHOT` and it also works for this issue. :)

Would be interested to know what the problem is. Maybe @dukke can help here or shed some light on it? :)
