### ISSUE TITLE
Question: Howto change the colour for each point ScatterAndBubbleRenderer 

### ISSUE THREAD

**Issue by osaidmakhalfeh** [GSI-CS-CO/chart-fx#233]
Hi Everyone,
Thanks for this amazing effort.

I'm trying to simulate this chart using the example of ScatterAndBubbleRenderer.

![image](https://user-images.githubusercontent.com/44381968/90755114-795fda80-e2e3-11ea-8b6f-6c2a61a7dd76.png)

I want to give a color for each point on the chart, not for the whole data set. 
My input is about 100,000 coordinates of three parameters (color, x,y).

Any ideas, please!

Thanks a lot

**Comment by osaidmakhalfeh** [comment]
I used ScatterAndBubbleRendererSample example and that worked with me.
Thanks a lot.

**Comment by RalphSteinhagen** [comment]
Glad to hear that this helped! Enjoy!
