### ISSUE TITLE
Custom axis label font overriden by CSS

### ISSUE THREAD

**Issue by tanrikut** [GSI-CS-CO/chart-fx#236]
Changing axis label font with `axis.getAxisLabel().setFont(font)` doesnt work. It is overriden by CSS.

Workaround for this  is to set style as following:

```
xAxis.getAxisLabel().setStyle("-fx-font-family: " + font.getFamily() + "; -fx-font-size: " + font.getSize()
				+ ";-fx-font-weight: " + (font.getStyle().toLowerCase().contains("bold") ? "bold" : "normal") + ";");
````

**Comment by wirew0rm** [comment]
Thanks for the report and sorry for coming back to this so late.

I can reproduce the issue, another way to fix it is to remove the `-axis-label` section from `chart.css`.

From the [CSS-Reference guide](https://docs.oracle.com/javase/8/javafx/api/javafx/scene/doc-files/cssref.html#introstylesheets):

> The implementation allows designers to style an application by using style sheets to override property values set from code. For example, a call to rectangle.setFill(Color.YELLOW) can be overridden by an inline‑style or a style from an author stylesheet. This has implications for the cascade; particularly, when does a style from a style sheet override a value set from code? The JavaFX CSS implementation applies the following order of precedence: a style from a user agent style sheet has lower priority than a value set from code, which has lower priority than a Scene or Parent style sheet. Inline styles have highest precedence. Style sheets from a Parent instance are considered to be more specific than those styles from Scene style sheets.

This aligns with your observations. Unfortunately `chart.getStylesheets().clear()` does not help, the property keeps its "css overridden" state (additionally you loose a lot of other needed styling, e.g. the zoom rectangle).
Moving to user agent stylesheet is also difficult, as it is not inherited by children and it is controlled by overriding the method, so we cannot add it to generic child nodes without subclassing.

The only real fix i see is to move the property from `chart.css`to an `example.css` and provide the defaults in the code. This is probably true for all properties affected by the current content of `chart.css`. At the same time it would distribute the default styling of the chart to lots of different places and make things like providing a dark and light theme more difficult.

**Comment by wirew0rm** [comment]
We removed the font from the default css, this should solve this specific problem, but of course there might be other instances of this. The fix will be merged into master and released soon.

**Comment by RalphSteinhagen** [comment]
@tanrikut the commit is now in master. Quick question: does the commit solve your issue?

Thanks again for posting this issue! :+1:
