### ISSUE TITLE
Changing horizontal minor grid line visibility doesnt refresh chart

### ISSUE THREAD

**Issue by tanrikut** [GSI-CS-CO/chart-fx#237]
Calling `xyChart.getGridRenderer().getHorizontalMinorGrid().setVisible(visibility);` doesnt update the chart visual whereas changing major axis visibility updates the chart `xyChart.getGridRenderer().getHorizontalMajorGrid().setVisible(visibility);`

**Comment by wirew0rm** [comment]
solved on the development branch, will be merged and released soon, thanks for reporting :+1:

**Comment by tanrikut** [comment]
Thanks
