### ISSUE TITLE
The dependencies are massive

### ISSUE THREAD

**Issue by ennerf** [GSI-CS-CO/chart-fx#28]
Our JavaFX application needs to be distributed to clients as a standalone version, i.e., including a runtime and all dependencies. Unfortunately, adding ChartFX turns a 45MB distributable into almost 90MB. This means that ChartFX alone currently is the same size as an entire JRE with OpenJFX and a decently complex application.

Using the [maven-shade-plugin](https://maven.apache.org/plugins/maven-shade-plugin/) on `chartfx-chart` creates a massive uber-jar with **77.4MB**:

```
[INFO] Including org.openjfx:javafx-controls:jar:12.0.1 in the shaded jar.
[INFO] Including org.openjfx:javafx-controls:jar:win:12.0.1 in the shaded jar.
[INFO] Including org.openjfx:javafx-graphics:jar:12.0.1 in the shaded jar.
[INFO] Including org.openjfx:javafx-graphics:jar:win:12.0.1 in the shaded jar.
[INFO] Including org.openjfx:javafx-swing:jar:12.0.1 in the shaded jar.
[INFO] Including org.openjfx:javafx-swing:jar:win:12.0.1 in the shaded jar.
[INFO] Including org.openjfx:javafx-fxml:jar:12.0.1 in the shaded jar.
[INFO] Including org.openjfx:javafx-fxml:jar:win:12.0.1 in the shaded jar.
[INFO] Including de.gsi.dataset:chartfx-dataset:jar:11.0.1-SNAPSHOT in the shaded jar.
[INFO] Including it.unimi.dsi:fastutil:jar:8.2.3 in the shaded jar.
[INFO] Including de.gsi.math:chartfx-math:jar:11.0.1-SNAPSHOT in the shaded jar.
[INFO] Including org.apache.commons:commons-math3:jar:3.6.1 in the shaded jar.
[INFO] Including org.jfxtras:jfxtras-labs:jar:8.0-r5 in the shaded jar.
[INFO] Including org.jfxtras:jfxtras-agenda:jar:8.0-r5 in the shaded jar.
[INFO] Including org.jfxtras:jfxtras-controls:jar:8.0-r5 in the shaded jar.
[INFO] Including org.jfxtras:jfxtras-common:jar:8.0-r5 in the shaded jar.
[INFO] Including org.jfxtras:jfxtras-fxml:jar:8.0-r5 in the shaded jar.
[INFO] Including org.controlsfx:controlsfx:jar:11.0.0 in the shaded jar.
[INFO] Including org.openjfx:javafx-base:jar:11 in the shaded jar.
[INFO] Including org.openjfx:javafx-base:jar:win:11 in the shaded jar.
[INFO] Including org.openjfx:javafx-media:jar:11 in the shaded jar.
[INFO] Including org.openjfx:javafx-media:jar:win:11 in the shaded jar.
[INFO] Including org.openjfx:javafx-web:jar:11 in the shaded jar.
[INFO] Including org.openjfx:javafx-web:jar:win:11 in the shaded jar.
[INFO] Including de.codecentric.centerdevice:javafxsvg:jar:1.3.0 in the shaded jar.
[INFO] Including org.apache.xmlgraphics:batik-transcoder:jar:1.8 in the shaded jar.
[INFO] Including org.apache.xmlgraphics:batik-anim:jar:1.8 in the shaded jar.
[INFO] Including org.apache.xmlgraphics:batik-css:jar:1.8 in the shaded jar.
[INFO] Including org.apache.xmlgraphics:batik-ext:jar:1.8 in the shaded jar.
[INFO] Including org.apache.xmlgraphics:batik-parser:jar:1.8 in the shaded jar.
[INFO] Including org.apache.xmlgraphics:batik-svg-dom:jar:1.8 in the shaded jar.
[INFO] Including org.apache.xmlgraphics:batik-awt-util:jar:1.8 in the shaded jar.
[INFO] Including org.apache.xmlgraphics:batik-bridge:jar:1.8 in the shaded jar.
[INFO] Including org.apache.xmlgraphics:batik-script:jar:1.8 in the shaded jar.
[INFO] Including xalan:xalan:jar:2.7.0 in the shaded jar.
[INFO] Including org.apache.xmlgraphics:batik-dom:jar:1.8 in the shaded jar.
[INFO] Including org.apache.xmlgraphics:batik-gvt:jar:1.8 in the shaded jar.
[INFO] Including org.apache.xmlgraphics:batik-svggen:jar:1.8 in the shaded jar.
[INFO] Including org.apache.xmlgraphics:batik-util:jar:1.8 in the shaded jar.
[INFO] Including org.apache.xmlgraphics:batik-xml:jar:1.8 in the shaded jar.
[INFO] Including xml-apis:xml-apis:jar:1.3.04 in the shaded jar.
[INFO] Including xml-apis:xml-apis-ext:jar:1.3.04 in the shaded jar.
[INFO] Including org.apache.xmlgraphics:xmlgraphics-commons:jar:2.1 in the shaded jar.
[INFO] Including commons-io:commons-io:jar:1.3.1 in the shaded jar.
[INFO] Including commons-logging:commons-logging:jar:1.0.4 in the shaded jar.
[INFO] Including com.ibm.icu:icu4j:jar:63.1 in the shaded jar.
[INFO] Including org.slf4j:slf4j-api:jar:1.7.25 in the shaded jar.
```

## Dependency Sizes

Selectively including individual artifact groups yields the following (bold highlighting indicates that they'd be easy to get rid of):

* **`org.openjfx:javafx-web`: 23.3MB**
* **`it.unimi.dsi:fastutil`: 19MB**
* **`com.ibm.icu:*`: 13MB**
* `org.openjfx:*`: 11MB (without web)
* **`org.apache.xmlgraphics:*`: 3.6MB**
* **`xalan:*`: 3.3MB**
* **`org.jfxtras:*`: 3MB**
* **`org.apache.commons:*`: 2.8MB**
* `de.gsi.*`: 1.7 MB
* `org.controlsfx:*`: 1.5MB
* **`xml-apis:*`: 1MB**
* `org.slf4j:*`: 0.7MB
* **`de.codecentric.centerdevice:*`: 0.6MB**

Total 84.2MB (each result includes the project jar, so each size is off by roughly 0.6MB)

## Suggestions

* `javafx-web` seems to be a transient compile dependency from `ControlsFX` that can probably be manually excluded by users. (23MB)

* `it.unimi.dsi:fastutil` is only used for the `DoubleArrayList` in `DoubleDataSet`. The used functionality can be implemented in a few lines of code (e.g. [DGrowArray](https://github.com/lessthanoptimal/ejml/blob/master/main/ejml-core/src/org/ejml/data/DGrowArray.java)), so it's probably worth duplicating it to get rid of ~20 (!!!) MB.

* `de.codecentric.centerdevice:javafxsvg` has a huge dependency tree (all of ` org.apache.xmlgraphics`, `xml-apis`, `xalan`, `commons-io`, `commons-logging`), but it's only used for loading svg images in the [ChartIconFactory](https://github.com/GSI-CS-CO/chart-fx/blob/82bec5a25fc724fce4d4dffc404d27e826185b30/chartfx-chart/src/main/java/de/gsi/chart/renderer/spi/utils/ChartIconFactory.java). Using downscaled `PNG` images would save another ~10 MB. Besides the size, adding >20 dependencies is also a big issue when using ProGuard for obfuscation/shrinking. There could be an extension point in case some users feel really strongly about using `svg`.

* `com.ibm.icu` is only used for the `DecimalFormat` in [NumberFormatterImpl](https://github.com/GSI-CS-CO/chart-fx/blob/81e879211f5c158f1ff22a45f3fdfb435cdc0b45/chartfx-chart/src/main/java/de/gsi/chart/utils/NumberFormatterImpl.java). I'm pretty sure that this could be replaced with Java's built-in [DecimalFormat](https://docs.oracle.com/javase/7/docs/api/java/text/DecimalFormat.html). (13MB).

* I did not find any use of `org.jfxtras` anywhere. This may be an unused dependency? Another 3MB

Not counting the OpenJFX packages, this would turn ChartFX into a much more reasonable **2-3MB** dependency.

Edit: It'd also be nice if `org.slf4j` could be turned into an optional dependency, similar to how it's done in other fx libraries (e.g. [AfterBurner.fx::Injector](https://github.com/AdamBien/afterburner.fx/blob/master/src/main/java/com/airhacks/afterburner/injection/Injector.java#L80-L82)). SLF4J is small, but it produces potentially unwanted output to the console, such as warnings if there is no configuration.

**Comment by wirew0rm** [comment]
Thanks for bringing this up, we're looking into it. Some preliminary remarks:

- javafx-web: removed with only minor changes
- fastutils: low usage because it was added only recently. "A type-specific array-based list; provides some additional methods that use polymorphism to avoid (un)boxing" <- our usecase, DGrowArray is missing a lot of features that we want to have + we want to concentrate on charting instead of primitive data types.
- svg: is an inhouse functional requirement (remaining pngs will also be migrated to vector based)
- jfxtras: currently used in DataViewer, will probably be removed after overhaul of that class.
- java's NumberFormatter is actually a lot less suited for formating axis labels, where we need to control the number of digits and dynamically switch to exponential representations. -> nontrivial change affecting core usecases of our library
- slf4j: slf4j is the standard logging solution in chart-fx's main application, so we will not get rid of it, but we aim to provide better out of the box experience by providing sample/default configuration.

**Comment by ennerf** [comment]
* fastutils: In my use case I assume that ProGuard can shrink away whatever isn't used, so I'm not all that worried about it. It does noticeably increase packaging time, but that's not a deal breaker.

* svg: I've spent several hours today trying to get all the dependencies sorted out in ProGuard, but so far I haven't managed to produce an executable that still works. I realize that this is a functional requirement for you, but would it be possible to turn this into an optional feature? For example,

```Java
// Pseudo code
static {
   // Use reflection to figure out if SvgImageLoaderFactory is on classpath
   // If so -> install support for .svg
}

public Image getIcon(String name) {
    try {
       return read(name + ".svg");
    }catch(cant-read-svg-exception e){
       return read(name + ".png");
    }
}
```

This way you automatically get svg support if the library is on the classpath, or if a user installs support in some other way. It's your library, so it's obviously your call, but if possible I'd really like to avoid having to maintain a fork. This seems like a really small change and I'm probably not the only user who will run into this.

**Comment by ennerf** [comment]
I was able to work around this by excluding everything that isn't absolutely necessary. My only remaining issue is that I've so far been unable to remove or shrink `com.ibm.icu`. ~15MB total is already a lot more reasonable though.
