### ISSUE TITLE
#Offtop

### ISSUE THREAD

**Issue by strelchm** [GSI-CS-CO/chart-fx#295]
Good afternoon, dear developers of chart-fx framework! Thanks for your work, because I spend much time for making timeaxis, several axis and other feauteres for signal processing in Fx, but you have made a very rich framework with all that I need. 

I have the question. I have seen that there is the swing framework JDataViewer that is opensource (from your IPAC 19 papers). But I can't find it in internet. Can you give me advice where I can find it? Your answer will help me much! I want to make app with large data and speed is very nessesary for me. So I want to make real time charts in maximum fast swing and history charts in chart-fx with maximum of features.
 
With honour, Strelchenko Michael!

**Comment by RalphSteinhagen** [comment]
@strelchm Chart-fx is a JavaFX based charting library development which in parts is based on the design of the JDataViewer. 

However, we are neither the maintainer, nor continue developing with, nor the original copyright holder of JDataViewer. For getting a copy of JDataViewer, may I suggest that you contact CERN directly via the official channel?

**Comment by strelchm** [comment]
Thanks much for an answer!
