### ISSUE TITLE
Data reduction removes outliers

### ISSUE THREAD

**Issue by ennerf** [GSI-CS-CO/chart-fx#31]
Tested on: `11.0.3`

When trying to render incoming real-time data, I noticed that sometimes outlier data points (highlighted by red) sometimes get removed by the reduction. 

![image](https://user-images.githubusercontent.com/5491587/64842408-73a54380-d602-11e9-834a-8d408d985f55.png)

**reduction enabled** (minPointPixelDistance = 0) 

https://youtu.be/V6WN-RcqSNE

**reduction disabled**

https://youtu.be/YczACfkoAVs

**Comment by ennerf** [comment]
* The behavior is the same when plotting lines in addition to the markers
* I'm using `ErrorDataSetRenderer` with the `DefaultDataReducer` and `DoubleErrorDataSet`s

**Comment by ennerf** [comment]
Also... I don't know where those total screen flickers are coming from. Should that be in the same issue?

**Comment by RalphSteinhagen** [comment]
Thanks! 

regarding the global flickering: known and issue solved in [dev branch](https://github.com/GSI-CS-CO/chart-fx/blob/90a0015459e6dc618b8796a28ac1be8c5fa3b861/chartfx-chart/src/main/java/de/gsi/chart/renderer/spi/ErrorDataSetRenderer.java#L142).

If I am not mistaken, the outliers are not flickering for the 'reduction disabled' case. Is this correct? If yes, then this points to the [reduction algorithm](https://github.com/GSI-CS-CO/chart-fx/blob/90a0015459e6dc618b8796a28ac1be8c5fa3b861/chartfx-chart/src/main/java/de/gsi/chart/renderer/datareduction/DefaultDataReducer.java#L152). 

Just to confirm: the data set is sorted/monotonic in X, isn't it?

**Comment by ennerf** [comment]
Yes, the data set is monotonically increasing in X. In case it matters: the blue line comes from microsecond resolution timers on an embedded device, so so the Y values are often exactly identical. Below is a zoomed-in view of a similar plot.

![image](https://user-images.githubusercontent.com/5491587/64844455-20ce8a80-d608-11e9-8a12-067badd996a1.png)

The other two lines have nanosecond resolution and more jitter, so they would rarely have the same value.

**Comment by RalphSteinhagen** [comment]
@ennerf could you check/confirm whether the outlier issue is fixed (e.g. with the version in master? If yes, you may close this issue (and add maybe a tag to the issue title accordingly).

The other issue #33 and #34 are kept and will follow-up them there. For the time being, we are working on to reproduce them reliably (existing test cases/samples didn't catch them :-| ).

**Comment by ennerf** [comment]
@RalphSteinhagen I just tested the latest version in the `dev-x.1.0` branch and it seems like the problem is fixed. Closing this issue. Thanks!

I'm not sure what you mean by adding a tag to the issue title?
