### ISSUE TITLE
Hyphen module name breaks module based projects

### ISSUE THREAD

**Issue by qballed** [GSI-CS-CO/chart-fx#321]
As per the JSE 9+ specs;

https://docs.oracle.com/javase/specs/jls/se9/html/jls-7.html#jls-ModuleDeclaration
https://docs.oracle.com/javase/specs/jls/se9/html/jls-3.html#jls-3.8

A module/package identifier, within the module descriptor(module-info.java) needs to be an alphanumeric string. The suggested workaround for module based projects is to use a period in place of the hyphen, for the "Automatic-Module-Name" in the manifest as such:

Automatic-Module-Name: de.gsi.chart.chartfx.chart

Further info on module resolution:

https://docs.oracle.com/javase/9/docs/api/java/lang/module/ModuleFinder.html

Love your work.

**Comment by wirew0rm** [comment]
Thank you for the report, we just reused our artifact id's without giving it enough thought.

As we do not have any modularized applications using chartfx: is this "just" a spec violation or does this actually stop you from using this in your module-info.java? Should be fixed anyway of course, but if users could already be using the current non-conforming module name, we should communicate this differently.

**Comment by qballed** [comment]
Dependent applications wont compile so it's more than just a spec violation. This is the following javac error on both Oracle 11.0.7 and OpenJDK-11.0.3. 

error: cannot access module-info
  cannot resolve modules

Amending the manifest as per above works fine.

**Comment by wirew0rm** [comment]
Thanks for the clarification, prepared a pull request which will be merged as soon as CI passes.
