### ISSUE TITLE
I need docs to create realtime charts.

### ISSUE THREAD

**Issue by masa2146** [GSI-CS-CO/chart-fx#334]
Hi, I wanna create a realtime chart using by chartfx. I've examined your FinancialRealtimeCandlestickSample codes but it very complex for me and it does not work. Do you have a docs suggestion to create realtime chart.

**Comment by RalphSteinhagen** [comment]
Hi @masa2146! First, thanks for your interest in Chart-FX!

You may want to consult the examples and links on the [README.md](https://github.com/GSI-CS-CO/chart-fx/blob/master/README.md#code-example) page and specifically the examples in the samples [directory](https://github.com/GSI-CS-CO/chart-fx/tree/master/chartfx-samples/src/main/java/de/gsi/chart/samples).  I'd suggest that you run and try out these examples and to copy-paste the bits that you like or need. 

We are using GitHub's new [discussion](https://github.com/GSI-CS-CO/chart-fx/discussions) feature. We'd like to use the [issue](https://github.com/GSI-CS-CO/chart-fx/issues) page for tracking bugs or missing/new functionalities. I will thus close this as bug issue. Please feel free to re-open if you find a bug and/or feel free to use the [discussion](https://github.com/GSI-CS-CO/chart-fx/discussions) page.

Enjoy!
