### ISSUE TITLE
Dev version Y axis still flickers

### ISSUE THREAD

**Issue by ennerf** [GSI-CS-CO/chart-fx#34]
The Y axis flicker issue still exists in the dev version.

Fixing the y axis results in a very smooth video: https://youtu.be/vuzG4XRBWAA

```Java
DefaultNumericAxis yAxis = new DefaultNumericAxis("Values", "");
yAxis.setAutoGrowRanging(false);
yAxis.setAutoRanging(false);
yAxis.setUpperBound(5);
yAxis.setLowerBound(0);
```

Enabling an auto-range still flickers: https://youtu.be/ZWjRCRhqp2I
(I did a comparison earlier. The left window is the older JChart2D version)

```Java
DefaultNumericAxis yAxis = new DefaultNumericAxis("Values", "");
yAxis.setForceZeroInRange(true);
yAxis.setAutoGrowRanging(true);
yAxis.setAutoRanging(true);
```

**Comment by ennerf** [comment]
I was able to catch a "flicker" in the `computeRange()` method for the Y axis. I tried the DoubleDataSet to make sure it's not something related to data being expelled.

```
(maxValue = 4.842600) previous AxisRange [min=0.000000, max=2.279550, axisLength=234.000000, scale=-102.651839, tickUnit=0.250000] next AxisRange [min=0.000000, max=4.842600, axisLength=234.000000, scale=-48.321150, tickUnit=0.500000] 
(maxValue = 4.842600) previous AxisRange [min=0.000000, max=4.842600, axisLength=223.000000, scale=-46.049643, tickUnit=0.500000] next AxisRange [min=0.000000, max=4.842600, axisLength=1025.000000, scale=-211.663156, tickUnit=0.250000] 
```

The max is the same, but somehow the axis length briefly got reported as `1025` instead of `~234`, which screws up the scaling. The app was in full-screen the entire time, so the axis length should be constant.

**Comment by RalphSteinhagen** [comment]
@ennerf: could you check if your use-case is still affected with the latest commit?

The commit related #33 may have solved this issue as well. Thanks in advance.

**Comment by ennerf** [comment]
Problem seems to be gone. Thanks!
