### ISSUE TITLE
Curve disappearing when zooming

### ISSUE THREAD

**Issue by thhart** [GSI-CS-CO/chart-fx#357]
When zooming in the curve disappears (even if data points are still in the zoomed in range). I tested with different versions.
Version: 11.2.3
JavaFx: 14 in Linux

The zoom plugin is used like this:
<pre>
              final de.gsi.chart.plugins.Zoomer zoomer = new de.gsi.chart.plugins.Zoomer(AxisMode.X);
              zoomer.setSliderVisible(false);
              chart.getPlugins().add(zoomer);
</pre>

**Comment by wirew0rm** [comment]
This is probably not related to the Zoomer plugin but to the way the Renderer selects the visible points in the dataset when the visible range is smaller than the complete data range.
Can you test this with `chart.getRenderers().get(0).setReducePoints(false)` and/or `chart.getRenderers().get(0).setAssumeSortedData(false)`? Are your data's x-values sorted (ascending)?

**Comment by thhart** [comment]
Thanks a lot, sorting the data in front did the trick. I can not judge if this is a wanted behaviour. Is so please close the issue.

**Comment by wirew0rm** [comment]
It is kind of necessary if you want to have good performance with large datasets and high update rates. That is also why we added these escape hatches to allow showing unsorted data (by sacrificing performance). It should probably be made more obvious in the documentation.
