### ISSUE TITLE
Applications don't close due to user threads in executor service

### ISSUE THREAD

**Issue by ennerf** [GSI-CS-CO/chart-fx#36]
Applications that have the parallell rendering implementation enabled don't automatically stop on `Platform::exit` because the executor service creates user threads rather than daemon threads.

I wasn't sure where to put it, but it could be fixed pretty easily with

```Java
private static final ThreadFactory DAEMON_THREAD_FACTORY = new ThreadFactory() {
        private final ThreadFactory defaultFactory = Executors.defaultThreadFactory();
        @Override
        public Thread newThread(Runnable r) {
            Thread thread = defaultFactory.newThread(r);
            thread.setDaemon(true);
            return thread;
        }
    };

private static final ExecutorService EXECUTOR_SERVICE = Executors.newFixedThreadPool(2 * MAX_THREADS, DAEMON_THREAD_FACTORY);
```

I found two Executors, one in `EventThreadHelper` and one in  `CachedDataPoints`.

**Comment by RalphSteinhagen** [comment]
added fix as suggested above. JavaFX thread terminates but there are some unknown 'ForkJoinPool.commonPool-worker-' remaining. 
Couldn't find any remaining explicite calls to 'ForkJoinPool...'

**Comment by ennerf** [comment]
Maybe the `parallelStream()` in [XYChart](https://github.com/GSI-CS-CO/chart-fx/blob/dev-x.1.0/chartfx-chart/src/main/java/de/gsi/chart/XYChart.java#L247)

See https://dzone.com/articles/be-aware-of-forkjoinpoolcommonpool

**Comment by RalphSteinhagen** [comment]
switched from `parallelStream()` to `stream()`. Still the same result.... must be elsewhere. 
Besides, Java does/should close/daemonize their own ForkJoinPool threads for consistency.

**Comment by ennerf** [comment]
Yes, the application closes as expected with your latest changes, so this issue is already resolved.
