### ISSUE TITLE
Fixed axis range does not work with inverted axis

### ISSUE THREAD

**Issue by ennerf** [GSI-CS-CO/chart-fx#383]
Version: `chart-fx 11.2.5`

I'm trying to create a chart with a fixed range on an inverted axis. Creating a non-inverted one works

```Java
Chart chart = new XYChart();
Axis xAxis = chart.getFirstAxis(Orientation.HORIZONTAL);
xAxis.setAutoRanging(false);
xAxis.setAutoGrowRanging(false);
xAxis.set(0, 100);

Axis yAxis = chart.getFirstAxis(Orientation.VERTICAL);
yAxis.setAutoRanging(false);
yAxis.setAutoGrowRanging(false);
yAxis.set(0, 10);
```

![image](https://user-images.githubusercontent.com/5491587/112686086-bf7ead00-8e75-11eb-831f-49dc322e4bb3.png)

but as soon as I add inversion, both X and Y axes are fixed to `[-1, +1]`. It does not matter whether it is only one axis or in which order the methods are called.

```Java
xAxis.invertAxis(true);
yAxis.invertAxis(true);
```

![image](https://user-images.githubusercontent.com/5491587/112686209-f5239600-8e75-11eb-90a2-3c8a5a28876a.png)

**Comment by RalphSteinhagen** [comment]
@ennerf thanks for reporting. 

I made a simple MVP sample `SimpleInvertedChartSample.java' to reproduce and fix this issue -- actually by removing a seemingly superfluous 'clear()' when inverting the axis. For the auto-ranged axes, these cleared values are re-written thus the feature you observed.

This seems to solve the issue at least for the above case. Would you be willing to review the PR and check if there are other related corner use-cases? Thanks in advance.

**Comment by ennerf** [comment]
I can't test with my original application, but the examples work :+1:
