### ISSUE TITLE
Panner doesn't recover with right-click

### ISSUE THREAD

**Issue by ennerf** [GSI-CS-CO/chart-fx#39]
It's not a big issue, but just something that I've run into from time to time. I always use the Zoomer/Panner plugins together and typically use them like this:

**Zoom-first**
* zoom in somewhere
* pan around
* right-click -> returns back to original view

However, when the panner is used first (maybe to better see something on an edge) the default view can't be recovered via right-click, and the chart needs to be reset via the menu button.

**Pan-first**
* pan somewhere
* zoom in
* pan around
* right click -> returns to the state after the first panning step
* (be confused for a second)
* press the menu button -> returns back to original view

**Comment by RalphSteinhagen** [comment]
Panner does not implement a stack (Deque) of zoomed/shifted view ranges but modifies the axis ranges directly. Thus the inconsistency. 

We will think about whether to either add another stack  (synchronised between Panner/Zoomer) and/or merge the panner with the Zoomer since the functionality is very similar.

**Comment by ennerf** [comment]
As a quick workaround it'd also work to have right-click reset to the default view if the zoom stack is empty

**Comment by RalphSteinhagen** [comment]
Added the panner functionality to the Zoomer plugin. Can be configured via a booleanProperty (+setter/getter). Needs some testing w.r.t. secondary effects.

**Comment by ennerf** [comment]
Seems to work well. I haven't run into any unexpected effects yet
