### ISSUE TITLE
white thing on hover? [A: it's the 'HiddenSidesPane']

### ISSUE THREAD

**Issue by mgroth0** [GSI-CS-CO/chart-fx#419]
First of all, awesome library! JavaFX's default charts pale in comparison to this.

I literally just started using the library, so apologies if this is more of a newbie question

**Describe the bug**

A weird white thing appears on hover (mouseover) near the figure title. I wish I could explain better, but I'm not really sure what's going on.

**To Reproduce**
1. Create a figure
2. Mouseover near the title 

**Environment:**
 - OS: MacOS Big Sur
 - Java version: 16
 - JavaFx version: 17
 - ChartFx version: 11.1.5

Normal:

![Screen Shot 2021-05-17 at 1 59 42 AM](https://user-images.githubusercontent.com/12831489/118439231-8dd6d500-b6b3-11eb-9dc0-4d677c094685.png)

On hovering title:

![Screen Shot 2021-05-17 at 1 59 58 AM](https://user-images.githubusercontent.com/12831489/118439247-97f8d380-b6b3-11eb-8d5e-985a01f6bbc1.png)

Notice that strange thing above the title. Now its not super bad here, but I actually use a dark .css that inverts everything (just quickly switched to the default css while looking into this). Here's what it looks like on my usual style:

Normal:
![Screen Shot 2021-05-17 at 2 02 13 AM](https://user-images.githubusercontent.com/12831489/118439393-e7d79a80-b6b3-11eb-82da-40761641f633.png)

Strange thing:
![Screen Shot 2021-05-17 at 2 02 32 AM](https://user-images.githubusercontent.com/12831489/118439414-f32ac600-b6b3-11eb-8935-6c98d621e42a.png)

**Comment by RalphSteinhagen** [comment]
@mgroth0 thanks for your interest in Chart-fx. 

What you see is actually the 'toolbar' (contained in the `HiddenSidesPane` pane) that contains the various interactors for the zoomer, parameter measurement, and other chart plugins. Have a look [here](https://github.com/GSI-CS-CO/chart-fx/discussions/401#discussioncomment-625868-permalink) if you want to disable this feature. Hope this helps

P.S. we are also available on [gitter](https://gitter.im/fair-acc/chart?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) or [discussions](https://github.com/GSI-CS-CO/chart-fx/discussions).

**Comment by mgroth0** [comment]
Thanks for the fast response. I'm excited to continue using this
