### ISSUE TITLE
Any way to change color scheme?

### ISSUE THREAD

**Issue by graynk** [GSI-CS-CO/chart-fx#42]
Hi, thanks for the great charting library.

Is there any way to change the color scheme to the one from default JavaFX charts? chart.css doesn't use the colors that I see on the screen and I see that `ErrorDataSetRenderer` uses static calls to `DefaultRenderColorScheme`, but doesn't seem to have a method to set another scheme. `DefaultRenderColorScheme` does have different color arrays as fields, but again, I see no way to change which one is used or to add my own. I'd also like to disable hatching and symbols and just draw the lines themselves. `FillPattern` seems to have "solid" as an option, but it's not used anywhere, as far as I can tell. Am I missing something?

As a side question: is there any way to break up the data inside one dataset? I'm getting series of independent readings from the same sensors over time and I don't want to create a bunch of new datasets for each one, as that would look confusing. So I want clear space to separate them, but by default the last point of the previous series and the first point of the new one would get connected, as if it's the same series (which makes sense of course, but it's not what I want). In vanilla JavaFX charts I could traverse the node path and replace `LineTo` with `MoveTo`, which was very cumbersome, but generally worked. What's the approach here?

**Comment by RalphSteinhagen** [comment]
You can change the colours via the DataSet::setStyle("strokeColor="+...) interface. Similarly, the fill colours etc. can be changed. 

Regarding breaking up data into multiple bursts/sub-datasets: in increasing order of complexity you have the option of using
  a) the [FragmentedDataSet](https://github.com/GSI-CS-CO/chart-fx/blob/master/chartfx-dataset/src/main/java/de/gsi/dataset/spi/FragmentedDataSet.java), or
  b) deriving your own data container from [AbstractDataSet]() to minimise the overhead/reusing some of the basic implementations, or
  c) the [DataSet](https://github.com/GSI-CS-CO/chart-fx/blob/master/chartfx-dataset/src/main/java/de/gsi/dataset/DataSet.java) interface directly which is another valid and great option to customise this to your own need in case you have already an existing data structure that handles your IO needs.
We use all the above depending on the specific internal use-cases.

N.B. we simplified/streamlined the 'DataSet' interface in line of multi-dimensional data treatment. So you may want to have a look at the 'x.1.0' dev branch

**Comment by RalphSteinhagen** [comment]
@graynk ... have a look at [CustomColourSchemeSample](https://github.com/GSI-CS-CO/chart-fx/blob/dev-x.1.0/chartfx-samples/src/main/java/de/gsi/chart/samples/CustomColourSchemeSample.java)

**Comment by graynk** [comment]
> When I run it nothing happens after `primaryStage.show()` and no window appears. No exceptions thrown either, nothing

Quick debug showed that after `primaryStage.show()` it gets stuck here on line 149, so a lock has not been released somewhere?
https://github.com/GSI-CS-CO/chart-fx/blob/425a8ea024bbcd4cbf14106d7dc6febd0ec9622c/chartfx-dataset/src/main/java/de/gsi/dataset/spi/FragmentedDataSet.java#L147-L162

There's also a copy-paste typo that I found, it should be `setUnit` here

https://github.com/GSI-CS-CO/chart-fx/blob/425a8ea024bbcd4cbf14106d7dc6febd0ec9622c/chartfx-chart/src/main/java/de/gsi/chart/axes/spi/AbstractAxisParameter.java#L1303

**Comment by graynk** [comment]
Ok, so I nailed down the problem with lock. It's these two lines:
https://github.com/GSI-CS-CO/chart-fx/blob/425a8ea024bbcd4cbf14106d7dc6febd0ec9622c/chartfx-chart/src/main/java/de/gsi/chart/renderer/spi/ErrorDataSetRenderer.java#L143-L144
It first acquires read lock, and then on the first line of lambda tries to acquire write lock in `getIndex`

**Comment by wirew0rm** [comment]
Hey, thanks for hunting down this locking bug, getXindex does not do any changes to the dataSet and should not require a write lock. I fixed this along with the copy/paste bug in df31ebd.

As for separating the data sets, this is currently not implemented in our renderers. I think what Ralph was trying to say was that you can use the FragmentedDataSet to manage all your DataSets as one DataSet but then have some code add the individual DataSets to a renderer and copy the styles from the container dataSets.

What you could do is to subclass one of the existing renderers (DoubleErrorDataSetRenderer is the default one) and override its render() function. There you can then check for FragmentedDataSet and call a DoubleErrorDataSetRenderer for all non fragmented data sets and for each of the sub-datasets (after copying the styles from the FragmentedDataSet).

**Comment by wirew0rm** [comment]
You could use something like this. While hacking this together i found out that FragmentedDataSet does not expose its child data sets, but that is something that we can definitely change (to run this code i just added a getter).

```java
        ErrorDataSetRenderer renderer = new ErrorDataSetRenderer() {
            @Override
            public void render(final GraphicsContext gc, final Chart chart, final int dataSetOffset,
                    final ObservableList<DataSet> datasets) {
                ObservableList<DataSet> filteredDataSets = FXCollections.observableArrayList();
                for (DataSet ds : datasets) {
                    if (ds instanceof FragmentedDataSet) {
                        final FragmentedDataSet fragDataSet = (FragmentedDataSet) ds;
                        for (DataSet innerDataSet : fragDataSet.getDatasets()) {
                            // TODO: copy style from main dataSet
                            filteredDataSets.add(innerDataSet);
                        }
                    } else {
                        filteredDataSets.add(ds);
                    }
                }
                super.render(gc, chart, dataSetOffset, filteredDataSets);
            }
        };
        chart.getRenderers().clear();
        chart.getRenderers().add(renderer);
```

Alternatively you could also implement a similar approach adding all datasets into one LabeledDataSet and use labels to mark the "gaps" in your data st the renderer can omit them.

**Comment by wirew0rm** [comment]
see sample in 52b73118e6fecf4d42fc3174bb2768acdb688150

**Comment by graynk** [comment]
> You could use something like this. While hacking this together i found out that FragmentedDataSet does not expose its child data sets, but that is something that we can definitely change (to run this code i just added a getter).

I ended up using this approach in combination with `fragDataSet.setStyle("strokeColor=")`, thus adding only `innerDataSet.setStyle(fragDataSet.getStyle())` to the render sample. Not sure how to combine it with `DefaultRenderColorScheme.strokeColorProperty()` but it works anyway, thank you for the fast responses.

**Comment by graynk** [comment]
It'd be also nice to style X/YRangeIndicators, since I need several of them with different colors (there's public `setStyleClasses` now, but not `setStyleClass`), but that's beside the issue, I can make it public in my own fork. Thanks again for all your help.

**Comment by wirew0rm** [comment]
You can use e.g. `innerDataSet.setStyle("dsIndex=0")` to force all datasets to use the first entry of the color scheme.
