### ISSUE TITLE
`DataPointTooltip` tie-breaking does not agree with `ErrorDataSetRenderer` rendering order

### ISSUE THREAD

**Issue by domenicquirl** [GSI-CS-CO/chart-fx#454]
When multiple signals are close to each other, cross or otherwise overlap, the `ErrorDataSetRenderer` renders them front to back:

https://github.com/GSI-CS-CO/chart-fx/blob/23e7422bcf08ceb9291660785d54cb5f51b75970/chartfx-chart/src/main/java/de/gsi/chart/renderer/spi/ErrorDataSetRenderer.java#L167-L170

Therefore, in some places in the code I insert data sets that I want to be on top at the front of the renderer's data sets. However, the distance comparison in `DataPointTooltip` tie-breaks in favour of _later_ data sets in the renderers' lists:

https://github.com/GSI-CS-CO/chart-fx/blob/23e7422bcf08ceb9291660785d54cb5f51b75970/chartfx-chart/src/main/java/de/gsi/chart/plugins/DataPointTooltip.java#L114

Because of this, when I move series to the top in a chart and then hover one of the series' data points, the tooltip that shows is for the lowest data set that is rendered at this point. This is very much not ideal. Replacing the `<` with `<=` in the line linked above makes rendering order and tooltip agree. Unfortunately though, the comparison is inside a `private` implementation and is not overridable or otherwise customizable (not that I can think of many other important customizations that would apply, but for testing I copy-pasted the entire plugin), so I'm having a hard time to come up with alternative work-arounds.

(Side note: I am not particularly confident in the `<=` either, since it's an exact floating-point comparison. Maybe inverting the condition and the resulting action is better? Epsilon comparisons with greater epsilons do not seem applicable here.)

**Environment:**
 - OS: Windows
 - Java version: AdoptOpenJDK 15.0.2.7-hotspot
 - JavaFx version: OpenJFX 15.0.1
 - ChartFx version: 11.2.5

**Comment by RalphSteinhagen** [comment]
@domenicquirl thanks for investigating this. Would you be willing to make a PR for this? 

At the same time, you may change the `private` function signatures to `protected` (where needed). The `private` declarations are from a by-gone era...

**Comment by domenicquirl** [comment]
Are you fine with changing the comparison? I can update the signatures anyways, just I'll not get to the PR today. If you agree with this solution, I'll PR it tomorrow.

**Comment by RalphSteinhagen** [comment]
@domenicquirl we are always open to PRs! 

It's probably also easier to modify the primary source code and reproduce/validate with the samples than to make a work-around.  This library isn't the bible and may have bugs/features as any other software project. :smirk:

Looking forward. :+1:

**Comment by domenicquirl** [comment]
Sure, I did not intend to call that into question. Just wanted to double-check my suggested change since it may visibly change the current behaviour. Also I haven't needed to check out the `chart-fx` source until now, will do and make the change.

**Comment by RalphSteinhagen** [comment]
> Sure, I did not intend to call that into question.

No worries... we don't bite ... at least as long as I am fed. :smirk: 

Please feel free to post or refer to your application so that others can get inspired and/or learn from your use of chart-fx.
