### ISSUE TITLE
new problem arising with slf4j

### ISSUE THREAD

**Issue by j-gignoux** [GSI-CS-CO/chart-fx#459]
Hello
We have been using chartfx happily within our project for more than one year now, but got a new bug last night, likely in relation with your recent upgrade of the slf4j API. With a code that worked until yesterday, we now get this exception:

```
Unexpected problem occured during version sanity check
Reported exception:
java.lang.AbstractMethodError: Receiver class org.slf4j.simple.SimpleServiceProvider does not define or inherit an implementation of the resolved method 'abstract java.lang.String getRequestedApiVersion()' of interface org.slf4j.spi.SLF4JServiceProvider.
	at org.slf4j.LoggerFactory.versionSanityCheck(LoggerFactory.java:297)
	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:141)
	at org.slf4j.LoggerFactory.getProvider(LoggerFactory.java:421)
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:407)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:356)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:382)
	at de.gsi.chart.ui.css.CssPropertyFactory.<clinit>(CssPropertyFactory.java:24)
	at de.gsi.chart.axes.spi.AbstractAxisParameter.<clinit>(AbstractAxisParameter.java:43)

```
caused by this call to constructor of DefaultNumericAxis `DefaultNumericAxis newAxis = new DefaultNumericAxis("", "");`

slf4j is great but keeps causing this kind of bug here and there at version upgrades...
Do you know if there is a simple solution to this (e.g. upgrade some obscure other dependency)? We are using eclipse and manage our dependencies with ant/ivy, by the way.

thanks
J. Gignoux

**Comment by wirew0rm** [comment]
Hey,

I'm not sure why you would get this problem now, the last release of chartfx is from may and the last time the slf4j version was bumped is 2y (and many releases) ago. From/to which version did you upgrade? Or are you using chartfx from the master branch?
I have no experience with ant/ivy, but I assume that you can somehow get a list/tree of the resolved dependencies (alternatively check the classpath of the java command). Please check the versions of all slf4j and chartfx related jars.

Without knowing more about your project, my guess is that something in your dependency tree changed and it now resolves slf4j from another dependency with a version <2.0.0. Try explicitly adding a direct dependency to `org.slf4j:slf4j-api:2.0.0-alpha0` to your project. You might also have to bump the version of the actual logging provider (slf4j-simple, slf4j-log4j12 or whatever your project uses). If there is no logging provider this should also be fine, falling back to the builtin nop-logger and suppressing all logging.

I hope this helps,
Alex

**Comment by j-gignoux** [comment]
OK - we've updated the charftx version in our ivy.xml file, but it's still unclear why it didnt cause problems earlier. Anyway, fixed. Thanks for your help.
