### ISSUE TITLE
AutoRangePadding w/ AutoRangeGrowing compounds every iteration

### ISSUE THREAD

**Issue by ennerf** [GSI-CS-CO/chart-fx#465]
**Describe the bug**
DefaultNumericAxis: AutoRangePadding does not work with AutoRangeGrowing

I'd expect the below code to start at [0,10] and over time grow to [0, max*1.05]. What happens is that it adds 5% at every iteration and compounds to [0,>1E24]. 

![image](https://user-images.githubusercontent.com/5491587/134386653-b5272ca7-86c8-4b61-b10d-df5d2f141ad9.png)

The range is further increased whenever the window is resized.

![image](https://user-images.githubusercontent.com/5491587/134386848-ba33a3d2-c3a3-4e26-a3f3-28e68dae3d86.png)

**To Reproduce**
 
``` java
public class AxisRangeCheck extends Application {

    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage primaryStage) throws Exception {

        var xAxis = new DefaultNumericAxis();
        var yAxis = new DefaultNumericAxis();
        var chart = new XYChart(xAxis, yAxis);

        yAxis.setAutoRangePadding(0.05);
        yAxis.setAutoRanging(false);
        yAxis.setAutoGrowRanging(true);
        yAxis.set(0, 10);

        var ds = new DoubleDataSet("", 1000);
        chart.getDatasets().addAll(ds);
        new Thread(() -> {
            for (int i = 0; i < 1000; i++) {
                ds.add(i, i);
                try {
                    TimeUnit.MILLISECONDS.sleep(20);
                } catch (InterruptedException e) {
                }
            }
        }).start();

        Scene scene = new Scene(chart, 800, 600);
        primaryStage.setScene(scene);
        primaryStage.show();

    }

}
```

**Environment:**
 - OS: Windows 10
 - Java version: Zulu 16
 - JavaFx version: 16
 - ChartFx version: 11.2.5

**Comment by wirew0rm** [comment]
I'm on it. This is a little bit complicated due to the way the auto ranging is performed by XYChart with the AbstractAxis interface and the AutoRangePadding is implemented in the DefaultNumericAxis by overwriting the autocomputed range, so at the moment there is no way to get the unpadded original range values.
