### ISSUE TITLE
Testdata that is loaded in the `ChartPerformanceGraph` sample seems to be is missing

### ISSUE THREAD

**Issue by hmf** [GSI-CS-CO/chart-fx#475]
**Describe the bug**
I am trying to execute this example:

https://github.com/GSI-CS-CO/chart-fx/blob/e684c8cbbe138cca2079bd2df4ca7751e0313214/chartfx-samples/src/main/java/de/gsi/chart/samples/ChartPerformanceGraph.java

but it fails because the test data is not found.

**To Reproduce**

Compile and run the example on your own project.  

I also looked for the files:

``` java
    val FILE1  = "./testdata/ChartPerformanceBenchmark25Hz_V8.1.1_JDK8u112.csv"
    val FILE2  = "./testdata/ChartPerformanceBenchmark25Hz_V11.1.1_JDK11_JFX13.csv"
    val FILE3  = "./testdata/ChartPerformanceBenchmark25Hz_V11.1.2_JDK11_JFX13.csv"
```
using GitHub's web interface but found nothing. I am assuming therefore that these are missing. Any way I can lay my hand on these or compatible ones?

**Environment:**
 - Ubuntu 20.04
 - Java version: 17
 - JavaFx version: 17
 - ChartFx version: 11.2.6

**Comment by wirew0rm** [comment]
I cannot reproduce this problem and the files are here: https://github.com/GSI-CS-CO/chart-fx/tree/master/chartfx-samples/src/main/resources/de/gsi/chart/samples/testdata

How do you start the sample? Are you maybe using an IDE which does not run the maven resource plugin prior to launching the sample? Without more information I can only speculate, what should be happening is that maven should copy the resource files to the target directory and then they should be loaded from there, so you should check if they are present there.

Hope this helps, Alex

**Comment by hmf** [comment]
@wirew0rm 

> I cannot reproduce this problem and the files are here: https://github.com/GSI-CS-CO/chart-fx/tree/master/chartfx-samples/src/main/resources/de/gsi/chart/samples/testdata

Blind as bat. Should have found these files. Anyway, the Git search failed because it searches content, not file name. Sorry about that. 

> How do you start the sample? 

I am using [Scala](https://www.scala-lang.org/) with the [Mill](https://github.com/com-lihaoyi/mill) build tool, so the problem is on my end. But I think I see what is wrong: on my end I did not use the full path class path in the resources directory. 

> Hope this helps

It has. Thank you very much Alex.
