### ISSUE TITLE
MultiArrayDouble not found

### ISSUE THREAD

**Issue by dbof10** [GSI-CS-CO/chart-fx#483]
**Describe the bug**
A clear and concise description of what the bug is. Please use the issue feature only for actual bugs. If you have usage questions or are unsure if/how a certain functionality is supported in chart-fx please use the [q&a secton in the discussions feature](https://github.com/GSI-CS-CO/chart-fx/discussions/categories/q-a) or our [gitter channel](https://gitter.im/fair-acc/chart).

**To Reproduce**
Steps to reproduce the behavior. Ideally the problem can be reproduced in the samples provided with chart-fx or by adapting them slightly. Alternatively provide a minimal working example.
 
``` java
public class DoubleGridDataSet extends AbstractGridDataSet<DoubleGridDataSet> implements DataSet3D {
    private static final long serialVersionUID = -493232313124620828L;

    protected transient double[][] grid; // grid values
    protected transient MultiArrayDouble[] values; // the values on the grid
    protected transient int[] shape; // the sizes of the grid for each dimension [nx, ny ...]
    protected transient int dataCount;
```
DoubleGridDataSet  is using MultiArrayDouble. however, MultiArrayDouble is not found in the project

**Environment:**
 - OS: [e.g. Ubuntu 20.04]
 - Java version:
 - JavaFx version: 
 - ChartFx version: [master, 11.2.2, ...]

**Comment by raven2cz** [comment]
In my opinion, it is generated class in the maven build process.

**Comment by RalphSteinhagen** [comment]
@raven2cz correct!

@dbof10 have you tried this running this?
```
mvn compile install
```

Hope this helps in your build environment.

**Comment by wirew0rm** [comment]
Also see [here](https://github.com/GSI-CS-CO/chart-fx/discussions/408).

**Comment by dbof10** [comment]
I tried and get this error

```
 Reactor Summary for chartfx master-SNAPSHOT:
[INFO]
[INFO] chartfx ............................................ SUCCESS [  0.276 s]
[INFO] chartfx-generate ................................... SUCCESS [  0.073 s]
[INFO] dataset ............................................ SUCCESS [  0.025 s]
[INFO] math ............................................... SUCCESS [  0.024 s]
[INFO] chartfx-chart ...................................... SUCCESS [  0.056 s]
[INFO] microservice ....................................... SUCCESS [  0.329 s]
[INFO] acc ................................................ FAILURE [  0.026 s]
[INFO] chartfx-samples .................................... SKIPPED
[INFO] report ............................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.166 s
[INFO] Finished at: 2022-01-17T09:18:13+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project chartfx-acc: Could not resolve dependencies for project de.gsi.acc:chartfx-acc:jar:master-SNAPSHOT: The following artifacts could not be resolved: de.gsi.chart:chartfx-chart:jar:master-SNAPSHOT, de.gsi:microservice:jar:master-SNAPSHOT: Could not find artifact de.gsi.chart:chartfx-chart:jar:master-SNAPSHOT -> [Help 1]
```
Can you suggest how to fix? also what is the recommended maven version for this project?

**Comment by wirew0rm** [comment]
Sorry for not replying earlier, this somehow escaped my attention. Were you successful in the meantime? 

The only things that I could suggest with the information i have is trying to clear your ~/.m2/repository and maybe compiling and installing the maven modules separately. Technically it even succeeded to build chart-fx, so I'm not sure why it is not found for the next build module.

**Comment by dbof10** [comment]
hi it works now. I copy sample source code and compile with library binary instead of building from source
