### ISSUE TITLE
TickLabel clashing and misalignment when rotated -90

### ISSUE THREAD

**Issue by karlduderstadt** [GSI-CS-CO/chart-fx#49]
Thanks for developing this awesome plotter! The performance and features are fantastic!

I noticed if I use setTickLabelRotation(-90) on the y-axis, the TickLabels frequently clash and are not centered on the tick mark locations. I realize this might be an unusual use, but I would like to put a set of charts in a VBox and link their x-axes. In this case, it is nice to rotate the y-axis labels, so that the x-axes always remain aligned. Otherwise, differences in the digit number will cause the charts to be offset.

Do you have a suggestion about how to resolve the tick label clashing and alignment for this orientation?

<img width="488" alt="Screenshot 2019-11-12 at 14 22 59" src="https://user-images.githubusercontent.com/17951396/68675369-035e6400-0558-11ea-9963-2f9a5535590a.png">

**Comment by RalphSteinhagen** [comment]
Thanks for your interest and for using our little library ... we wrote this out of necessity but are happy to see that this finds us also outside our little research domain.

The following proposal is a temporary work-around until we find/tested/deployed a better/cleaner solution:
``` Java
DefaultNumericAxis yAxis = [..]
AxisLabelFormatter defaultConverter = yAxis.getAxisLabelFormatter();
StringConverter<Number> modifiedConverter = new StringConverter<>() {
    @Override
    public String toString(Number object) {
        // N.B. added spaces before/after as work-around
        return " " + defaultConverter.toString(object) + " ";
    }

    @Override
    public Number fromString(String string) {
        return defaultConverter.fromString(string.trim());
    }
};
yAxis.setTickLabelFormatter(modifiedConverter);
```

Let me know if this helps your purposes. Thanks in advance

**Comment by karlduderstadt** [comment]
Thanks for the fast response as well as the suggestion and example code. I have implemented it and this does indeed make things a bit better in terms of the overlapping. It happens less frequently because there are more cases where every other tick label is missing due to the extra spaces. 

The alignment is still below the tick mark. I guess this might involve a more complex fix because if you have a 45 degree angle as I have seen in some of the examples, you probably wouldn't want to change the alignment. So I guess there would need to be a special rule for the -90 case.

I really appreciate you open sourcing your project, so others can benefit from your efforts. We are attempting to integrate your library into our analysis software that we use to classify and characterise the results from single-molecule fluorescence experiments in the life sciences.

I am eager to help with further testing if you have time to implement further changes.

**Comment by wirew0rm** [comment]
Another option to align your y-Axis would be to assign them a fixed width:
```
yAxis.setMinWidth(100);
```
You would have to play with the correct value here and there might always be corner cases where some label might be bigger. But you could always work around these by setting up a listener to all the axes' widthProperties and change the minWidth there. Another advantage is better readability compared to rotated text. On the downside this would take a little bit more space.

Thank you letting us know how you are using chart-fx, it is always nice and motivating to see real world usages of our code :)

**Comment by karlduderstadt** [comment]
This is a great suggestion. I have implemented what you described and it is working really well. 

As you suggested, I added a listener to the widthProperty of the yAxis for all stacked plots in my VBox. Then when the width of any of them changes, I find the max width among the charts and set all minWidths to match. This shifts those charts that have shorter tick mark labels to the right, so all the y-axes match.

However, I did have to subclass DefaultNumericAxis to gain access to the computePrefWidth method (in super class AbstractAxis), which otherwise was protected. I use an overriden version of this method to check the ideal calculated size for all the axis and take the max of these values.

When I simply used the widthProperty, the plots could only move to the right and would never reset to the left when the tick mark labels got shorter, which can happen when zooming in and out.

I agree that having the labels horizontal is much better for readability. So I think actually prefer this solution. Even thought it takes a little bit more space, everyone will have a 4K screen soon anyway :)

Thank you very much for your prompt and very helpful feedback and this wonderful charting library you have created. It is a huge improvement over the default JavaFX chart capabilities.

Should we go ahead and mark this as closed, or do you want to also improve the situation for the -90 orientation?

**Comment by RalphSteinhagen** [comment]
@karlduderstadt  thanks.
> Should we go ahead and mark this as closed, or do you want to also improve the situation for the -90 orientation?

This is a valid minor but nevertheless, systematic bug (or better nuisance :smirk: ) that I'd like to fix before doing the next micro-release (x.1.1 -> target ~weekend/beginning next week).

We try to make the library better, one little commit at a time because this would have otherwise eventually popped-up in our internal use.

**Comment by RalphSteinhagen** [comment]
> I am eager to help with further testing if you have time to implement further changes.

@karlduderstadt thanks again for taking the time for testing and reporting this issue. This is valuable for steadily improving the lib where it matters. Would you be willing to re-test this issue? 

I fixed the underlying primary issue in the [feature branch](https://github.com/GSI-CS-CO/chart-fx/tree/VerticalTickLabelClash) and added a corresponding [RotatedAxisLabelSample.java](https://github.com/GSI-CS-CO/chart-fx/blob/VerticalTickLabelClash/chartfx-samples/src/main/java/de/gsi/chart/samples/RotatedAxisLabelSample.java) illustrating/testing the various `AxisLabelOverlapPolicy`options.

I also added an option to increase the number of max major tick labels via `setMaxMajorTickLabelCount(int)`.


> However, I did have to subclass DefaultNumericAxis to gain access to the computePrefWidth [..]

Your version is one of the valid options since the `computePrefWidth(double height)` access is defined/limited by the AbstractAxis parent `javafx.scene.layout.Region` version (which is protected).  Alternatively, you may listen to the actual `widthProperty()` and then set the 'setPrefWidth(..)` of each axis accordingly. You may also constrain the maximum width by setting the maximum width property.

**Comment by karlduderstadt** [comment]
Took me a little while to get everything running with JDK11 but then I found your helpful instructions at the bottom of the readme. I hadn't made the jump beyond JDK 8 until now.

I have tested the sample you developed and it looks great. Everything works very well for me in the sample. So the issue of -90 tick mark rotation appears to be completely solved and you included some further options which are very helpful. 

We are developing our software using java 8, so I couldn't test the tick mark rotation in my VBox easily, but I will certainly do that when the change makes it to the Java 8 branch. Then I can let you know if further issues arise when stacking plots.

Thanks for your very prompt response and great solution for this problem. I am happy if you want to close the issue based on your changes.

**Comment by RalphSteinhagen** [comment]
@karlduderstadt thanks for checking. 

We will merge this then into master (JDK11+), do a rebase for the JDK8 branch and release both accordingly.

**Comment by wirew0rm** [comment]
changes are in JDK8, not yet released, but you can either use from git or use the snapshot repository, e.g. with maven:

```
<dependency>
  <groupId>de.gsi.chart</groupId>
  <artifactId>chartfx-chart</artifactId>
  <version>JDK8-SNAPSHOT</version>
</dependency>
[...]
<repositories>
<repository>
  <id>oss.sonatype.org-snapshot</id>
  <url>http://oss.sonatype.org/content/repositories/snapshots</url>
  <releases>
    <enabled>false</enabled>
  </releases>
  <snapshots>
    <enabled>true</enabled>
  </snapshots>
</repository>
</repositories>
```
