### ISSUE TITLE
[Feature Suggestion] Sankey Plot

### ISSUE THREAD

**Issue by mgroth0** [GSI-CS-CO/chart-fx#522]
Like this:

https://github.com/HanSolo/sankeyplot

**Comment by wirew0rm** [comment]
Hey, thank you for the suggestion. We usually only implement things that we have a usecase of our own, so most probably this would have to be contributed as an external pull request, which we always welcome.

Also I'm not sure that/how it would fit chart-fx's dataset model which until now is mostly based on (2d,3d,...) points.

Why not use the library you linked for this kind of plot and chart-fx for the plots that are implemented here?

**Comment by wirew0rm** [comment]
Ok, thanks for the reply and sharing your experiences, should you decide you would need to implement it into chart-fx feel free to reopen or discuss this in gitter/matrix/discussions.
