### ISSUE TITLE
Connecting a chart to fxml

### ISSUE THREAD

**Issue by Vado101** [GSI-CS-CO/chart-fx#55]
Hello, everybody! How to connect a chart-fx to a hxml file? Show by example XYChart. Help me please.

**Comment by wirew0rm** [comment]
Hey,

we are currently working on making fxml support more straightforward, at the moment there are still a few pitfalls you have to deal with in native code.

I have added a (very simple) sample in one of our feature branches:

https://github.com/GSI-CS-CO/chart-fx/blob/feature-dataviewer-window-listener/chartfx-samples/src/main/java/de/gsi/chart/samples/FxmlSample.java
https://github.com/GSI-CS-CO/chart-fx/blob/feature-dataviewer-window-listener/chartfx-samples/src/main/resources/de/gsi/chart/samples/FxmlSample.fxml

Most of it should also work on master/last release, but for the axes some changes were necessary, which will be in the next release. (Default axes were added in the constructor and always had precedence over the manually added ones.)

**Comment by Vado101** [comment]
Thank you so much for the answer and the great charting library!

I will wait for the new version. Hope this helps me.

**Comment by wirew0rm** [comment]
You can already test the changes in the branch by using the snapshot release if you want to:

```
<dependency>
  <groupId>de.gsi.chart</groupId>
  <artifactId>chartfx-chart</artifactId>
  <version>feature-dataviewer-window-listener-SNAPSHOT</version>
</dependency>
[...]
<repositories>
<repository>
  <id>oss.sonatype.org-snapshot</id>
  <url>http://oss.sonatype.org/content/repositories/snapshots</url>
  <releases>
    <enabled>false</enabled>
  </releases>
  <snapshots>
    <enabled>true</enabled>
  </snapshots>
</repository>
</repositories>
```

There are a lot of different ways of setting up the chart so depending on how much you deviate from our samples there might be some cases which are still not supported from fxml. These might be missing default constructors/@NamedArg annotations or logic problems in the order required for setting up the chart. Please feel free to open a separate bug report if you encounter one of these, so we can fix them.
