### ISSUE TITLE
Is DataSet thread safe?

### ISSUE THREAD

**Issue by soloman817** [GSI-CS-CO/chart-fx#7]
I just tried this project, looks very good.

I want to dynamic add/remove points from dataset, and it works, but I was wondering if the dataset add method or remove method thread-safe, which I can call it from another thread (currently I'm using Akka actor)?

**Comment by soloman817** [comment]
@wirew0rm  thanks, I also saw the lock() invokation inside the DoubleDataSet code.

**Comment by RalphSteinhagen** [comment]
N.B. we are working on making chart-fx thread-safe. see e.g. #33
