### ISSUE TITLE
Linux: mouse wheel scroll-in not working

### ISSUE THREAD

**Issue by ennerf** [GSI-CS-CO/chart-fx#74]
**OS** 
Ubuntu 18.10

**Version** 
ChartFX 11.1.0
OpenJDK 13.0.1
OpenJFX 13.0.1

**Issue**
Scrolling in by using the mouse-wheel does not seem to work. Scrolling out produces the same behavior as on Windows and OSX.

I tried to debug this, but I didn't see anything obvious. The generated events look sane (deltaY is +40/-40), and the events aren't being filtered, i.e., setting the zoom-in/out and scroll filters to always return true does not fix it.

**Comment by RalphSteinhagen** [comment]
@ennerf I noticed that there are some other happy coders during the holiday seasons ... :smile: 
Unfortunately, I do not seem to be able to reproduce your observations using e.g. the [EditDataSetSample](https://github.com/GSI-CS-CO/chart-fx/blob/master/chartfx-samples/src/main/java/de/gsi/chart/samples/EditDataSetSample.java):

![vokoscreen-2019-12-28_09-39-32](https://user-images.githubusercontent.com/46007894/71541230-fbb31d00-2955-11ea-9fec-9ee8dac90d35.gif)

Could you perhaps recheck against the ChartFX master and/or 11.1.1 version? 

Just as a wild guess: do you perhaps use the (now deprecated) Panner in conjunction with the Zoomer plugin? In response to the issue #39 (commit https://github.com/GSI-CS-CO/chart-fx/commit/e22b9df8314425b02a1e6ed8772a6aa16859c2e7) we added and moved the Panner functionality to the Zoomer plugin to facilitate consistent zoom/drag/panner stack state. We kept the old Panner for reference, but the Zoomer can handle (configurably) both cases.

P.S. I need a better screengrabber/animated gif tool. The ones I have work, but are a bit clumsy.

**Comment by ennerf** [comment]
No, Zoomer is the only enabled plugin. Same issue on the 11.1.1 version.

If you can't reproduce it, I'll go ahead and close this issue. It's not a required feature, so I've disabled the mouse zoom entirely for now. I'm currently working on a different project, so I probably won't have time to get back to this for a few weeks.

Happy new year!

**Comment by RalphSteinhagen** [comment]
@ennerf sorry to hear that you had to disable the Zoomer plugin entirely. I'd be happy to fix this but couldn't find a starting point because of not being able to reproduce this feature because of either my specific 'user habits' or need for a bit more information on how to reproduce this.

Please feel free to reopen it.

**Comment by ennerf** [comment]
For clarification, the rest of the Zoomer plugin works fine. I just added a filter that removes the mouse-wheel-scroll events. As far as I know most users tend to be interested in specific areas, so the mouse-wheel-zoom is more of a gimmick anyways. I'll reopen if I find time to create a minimal sample to reproduce it.
