### ISSUE TITLE
Zoomer plugin regression: UnsupportedOperationException on clear

### ISSUE THREAD

**Issue by graynk** [GSI-CS-CO/chart-fx#78]
Hi again.

There was a regression introduced in 11.1.1, when underlying deque for zoomstacks in Zoomer was changed from ArrayDeque to ObservableDeque.
[Here](https://github.com/GSI-CS-CO/chart-fx/blob/114f4e0739460280e7f71adbbb10c6e03732e71b/chartfx-chart/src/main/java/de/gsi/chart/plugins/Zoomer.java#L342) it tries to clear zoomstacks, but ObservableDeque does not implement `clear` method, so it throws an exception (for me it happened when I set zoom origin filter, since when you try to zoom to origin, it clears zoomstacks).

**Comment by wirew0rm** [comment]
Hi, thanks for reporting this, I guess we never clicked on the reset zoom button.
We really need unit testing for stuff like this.

The fix will be merged soon and we will have a new release in the next few days.
Sorry for the inconvenience,

Alex
