### ISSUE TITLE
Negative Points are not registered by the DataPointTooltip Plugin

### ISSUE THREAD

**Issue by karlduderstadt** [GSI-CS-CO/chart-fx#79]
There appears to be a small typo in the DataPointTooltip Plugin between lines 155 and 157. Currently the code reads:
```java
final DataPoint nextPoint = nextIndex == -1 || nextIndex == prevIndex ? null
                : new DataPoint(getChart(), dataSet.get(DataSet.DIM_X, nextIndex),
                        dataSet.get(DataSet.DIM_X, nextIndex), getDataLabelSafe(dataSet, nextIndex));
```
This causes DataPoints to show up at the wrong location for some negative values and correct points not to be registered. Using the lines below seems to fix the issue:
```java
final DataPoint nextPoint = nextIndex == -1 || nextIndex == prevIndex ? null
                : new DataPoint(getChart(), dataSet.get(DataSet.DIM_X, nextIndex),
                        dataSet.get(DataSet.DIM_Y, nextIndex), getDataLabelSafe(dataSet, nextIndex));
```
basically the nextPoint was sent to (x, x) instead of (x, y). This issue only comes up for some ranges of values, so it is hard to spot.

**Comment by wirew0rm** [comment]
This will be merged in the next days, thanks for reporting :+1:

**Comment by karlduderstadt** [comment]
Awesome!
