### ISSUE TITLE
How to add dataset to different renderer?

### ISSUE THREAD

**Issue by soloman817** [GSI-CS-CO/chart-fx#9]
So, I want to have multiple dataset, some I want to plot with stair case, some I want to plot like matplotlib stem lines.

In the example, XYChart is created, and there is a default renderer there. So I have to create a new stair case renderer:

```
  val renderer = {
    val renderer = new HistoryDataSetRenderer()
    renderer.setPolyLineStyle(LineStyle.STAIR_CASE)
    chart.getRenderers.add(renderer)
    renderer
  }
```

now, If I call `chart.getDatasets().add(dataset)`, it will be rendered twice, if I call `renderer.getDatasets().add(dataset)` it only plot once. So what's the difference? If I want to render different dataset in the same chart differently, should I always call `renderer.getDatasets().add()`?

**Comment by wirew0rm** [comment]
Yes, that's correct, renderers(at least the ones that visualize datasets, not e.g. GridRenderer) always operate on their own dataset and on all datasets added to the chart.
